version: '3.8'

services:
  movies:
    #build do dockerfile
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #cria um "disco virtual" da imagem
    volumes:
      #guarda as infos do projeto
      - .:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - .env.dev